#%RAML 0.8
title: Sideband Notifications API
version: 1.0
baseUri: /mobile/custom/SidebandNotificationsAPI
protocols: [HTTPS]
mediaType: "application/json"
/loans:
  displayName: Loans
  description: |
    Loan notification profiles
    
  get:
    displayName: Loan
    description: |
      Create new loan notification profile
      
    protocols: [HTTPS]
  post:
    displayName: Loan
    description: |
      Create new loan notification profile
      
    protocols: [HTTPS]
    body:
      application/json:
  /{loanId}:
    displayName: Loan
    description: |
      Loan notification profile
      
    uriParameters:
      loanId:
        displayName: loanId
        description: |
          Unique ID of loan object
          
        type: string
        example: |
          7832d491-cc54-4d5e-9b0c-1b8b25e513d2
          
        required: true
    get:
      displayName: Loan
      description: |
        Get a loan notification profile
        
    put:
      displayName: Loan
      description: |
        Update a loan notification profile
        
      body:
        application/json:
    delete:
      displayName: Loan
      description: |
        Delete a loan notification profile
        
/dealers:
  displayName: Dealers
  description: |
    Automobile dealership contacts
    
  get:
    displayName: Dealers
    description: |
      Get all dealer objects
      
    protocols: [HTTPS]
  post:
    displayName: Dealer
    description: |
      Create a dealer object
      
    protocols: [HTTPS]
    body:
      application/json:
  /{dealerId}:
    displayName: Dealer
    description: |
      Automobile dealership contact
      
    uriParameters:
      dealerId:
        displayName: dealerId
        type: string
        required: true